const desc = {
    1: "An old prop from the Manitoba Museum, the hand is on private property across the Seine river from a public path, just inside the Perimeter highway.",
    2: "The antlers are right beside the greenway, a little west of Ste Anne’s Rd.",
    3: "The home of the Winnipeg Blue Bombers, on the University of Manitoba campus.",
    4: "The teepee is on the main walking/cycling path through Fort Whyte Alive.",
    5: "The Leaf is the newest attraction at Assiniboine Park. ",
    6: "This carving, just south of John Bruce Rd, is one of more than 20 that can be found along the trails in Bois Des Esprits.",
    7: "The Elm Park Bridge connects Kingston Crescent and Jubilee, next to a well-known ice cream venue.",
    8: "The kettle, at Beaumont station, is one of several pieces of public art along the Southwest transitway path.",
    9: "The Lyric Theatre is a popular venue in Assiniboine Park. ",
    10: "The deer lie at the corner of the William Clement Parkway and Grant Ave.",
    11: "The Saint Boniface Cathedral is across the Red River from The Forks.",
    12: "The Canadian Museum For Human Rights is the tallest building at The Forks.",
    13: "The Forks is a popular destination for summer patio fun and winter skating.",
    14: "The pavillion at Assiniboine Park is the park’s focal point and sits near the centre.",
    15: "A collection of old planes lies alongside Air Force Way, accessible via the Yellow Ribbon Greenway trail.",
    16: "The Transcona Bioreserve is a lovely greenspace off the Transcona Trail.",
    17: "Fort Gibraltar is a replica of a fur trading post in Whittier Park, close to a trail that links the Forks with the mouth of the Seine River.",
    18: "Shaw Park is the home of the Winnipeg Goldeyes and is near the start of the North Winnipeg Parkway trail.",
    19: "The Manitoba legislature is the grandest building in the city, and sits north of the bike trail that connects The Forks to West Broadway.",
    20: "Brookside Cemetery is a resting place for many war veterans, politicians and other renowned Winnipeggers. Next door is Red  River College, the end point of a few bike paths.",
    21: "The Transcona trail ends in a small loop next to the Perimeter highway.",
    22: "The Bunn’s Creek trail runs from the Northeast Pioneers Greenway to the Red  river.",
    23: "The wolves lie along Chief Peguis Trail a little east of the Red river.",
    24: "Rainbow Stage theatre sits near the Red River in Kildonan Park, close to the North Winnipeg Parkway trail.",
    25: "It’s not as grandiose as Stonehenge, but the concrete piles stacked together in circles here are a draw for the curious. The remnants of an old cement factory, this area is a few kilometres from any protected cycling infrastructure. Proceed with caution.",
}